package com.pactiv.pageobjects;

import org.openqa.selenium.By;

import com.pactiv.constants.Constants;
import com.pactiv.utils.PropertyUtils;

public class PactivLogin {
	public final String baseProjectPath = System.getProperty(Constants.USER_DIR);
	public final PropertyUtils repository = new PropertyUtils(
			baseProjectPath.concat(Constants.PACTIV_LOGIN_OBJECTREPOSITORY_PROPERTY));
//	 public final By pactiv_logo = By.xpath(repository.getProperty("PACTIV_LOGO"));
	public final By Username_Field = By.xpath(repository.getProperty("USERNAME_FIELD"));
	public final By password_field = By.xpath(repository.getProperty("PASSWORD_FIELD"));
	public final By submit_button = By.xpath(repository.getProperty("SUBMIT_BUTTON"));
	public final By logout_button = By.xpath(repository.getProperty("LOGOUT_BUTTON"));
//	 public final By usericon_button = By.xpath(repository.getProperty("USERICON_BUTTON"));
	public final By userinfo_button = By.xpath(repository.getProperty("USERINFO_BUTTON"));
	public final By supervisoruserprofile_button = By.xpath(repository.getProperty("SUPERVISORUSERPROFILE_BUTTON"));
	public final By userprofile_button = By.xpath(repository.getProperty("USERPROFILE_BUTTON"));
	public final By user_name_leadership = By.xpath(repository.getProperty("USER_NAME_LEADERSHIP"));
	public final By user_name_floater = By.xpath(repository.getProperty("USER_NAME_FLOATER"));
	public final By user_name_supervisor = By.xpath(repository.getProperty("USER_NAME_SUPERVISOR"));
	public final By user_name_eoh = By.xpath(repository.getProperty("USER_NAME_EOH"));
	public final By user_name_maintenance = By.xpath(repository.getProperty("USER_NAME_MAINTENANCE"));
	public final By user_role_leadership = By.xpath(repository.getProperty("USER_ROLE_LEADERSHIP"));
	public final By user_role_floater = By.xpath(repository.getProperty("USER_ROLE_FLOATER"));
	public final By user_role_supervisor = By.xpath(repository.getProperty("USER_ROLE_SUPERVISOR"));
	public final By user_role_eoh = By.xpath(repository.getProperty("USER_ROLE_EOH"));
	public final By user_role_maintenance = By.xpath(repository.getProperty("USER_ROLE_MAINTENANCE"));
	public final By username_plantmanager = By.xpath(repository.getProperty("USERNAME_PLANTMANAGER"));
	public final By username_supervisor = By.xpath(repository.getProperty("USERNAME_SUPERVISOR"));
	public final By username_floater = By.xpath(repository.getProperty("USERNAME_FLOATER"));
	public final By username_eoh = By.xpath(repository.getProperty("USERNAME_EOH"));
	public final By username_maintenance = By.xpath(repository.getProperty("USERNAME_MAINTENANCE"));
	public final By assigned_lines_leadership = By.xpath(repository.getProperty("ASSIGNED_LINES_LEADERSHIP"));
	public final By assigned_lines_eoh = By.xpath(repository.getProperty("ASSIGNED_LINES_EOH"));
	public final By assigned_lines_floater = By.xpath(repository.getProperty("ASSIGNED_LINES_FLOATER"));
	public final By assignedlines_zero = By.xpath(repository.getProperty("ASSIGNEDLINES_ZERO"));
	public final By alarm_toast = By.xpath(repository.getProperty("ALARM_TOAST"));
	public final By alarm_toast_multiple = By.xpath(repository.getProperty("ALARM_TOAST_MULTIPLE"));
	public final By report_toast = By.xpath(repository.getProperty("REPORT_TOAST"));
	public final By error_message = By.xpath(repository.getProperty("ERROR_MESSAGE"));
	public final By plantview_linedisconnected = By.xpath(repository.getProperty("PLANTVIEW_LINEDISCONNECTED"));
//	 public final By dashboard_icon = By.xpath(repository.getProperty("DASHBOARD_ICON"));
	public final By bridgeview_text = By.xpath(repository.getProperty("BRIDGEVIEW_TEXT"));
//	 public final By productiontracking_icon = By.xpath(repository.getProperty("PRODUCTIONTRACKING_ICON"));
//	 public final By activitylog_icon = By.xpath(repository.getProperty("ACTIVITYLOG_ICON"));
	public final By production_icon_plant = By.xpath(repository.getProperty("PRODUCTION_ICON_PLANT"));
//	 public final By report_icon = By.xpath(repository.getProperty("REPORT_ICON"));
	public final By activity_materialicon = By.xpath(repository.getProperty("ACTIVITY_MATERIALICON"));
	public final By notification_materialicon = By.xpath(repository.getProperty("NOTIFICATION_MATERIALICON"));
	public final By productiontracking_text = By.xpath(repository.getProperty("PRODUCTIONTRACKING_TEXT"));
	public final By productiontracking_text_supervisor = By
			.xpath(repository.getProperty("PRODUCTIONTRACKING_TEXT_SUPERVISOR"));
	public final By activity_icon_plant = By.xpath(repository.getProperty("ACTIVITY_ICON_PLANT"));
	public final By activitylog_text = By.xpath(repository.getProperty("ACTIVITYLOG_TEXT"));
	public final By notifications_icon = By.xpath(repository.getProperty("NOTIFICATIONS_ICON"));
	public final By notifications_text = By.xpath(repository.getProperty("NOTIFICATIONS_TEXT"));
	public final By userprofile_text = By.xpath(repository.getProperty("USERPROFILE_TEXT"));
	public final By materialhandlerview_text = By.xpath(repository.getProperty("MATERIALHANDLERVIEW_TEXT"));
	public final By activity_text_materialhandler = By.xpath(repository.getProperty("ACTIVITY_TEXT_MATERIALHANDLER"));
	public final By notifications_text_materialhandler = By
			.xpath(repository.getProperty("NOTIFICATIONS_TEXT_MATERIALHANDLER"));
	public final By reporttext_log = By.xpath(repository.getProperty("REPORTTEXT_LOG"));
	public final By reportlog_icon = By.xpath(repository.getProperty("REPORTLOG_ICON"));
	public final By userprofile_clearall = By.xpath(repository.getProperty("USERPROFILE_CLEARALL"));
	public final By userprofile_manual = By.xpath(repository.getProperty("USERPROFILE_MANUAL"));
	public final By userprofile_selectall = By.xpath(repository.getProperty("USERPROFILE_SELECTALL"));
	public final By clearall_okbutton = By.xpath(repository.getProperty("CLEARALL_OKBUTTON"));
//	 public final By warningmessage = By.xpath(repository.getProperty("WARNINGMESSAGE"));
//	 public final By userprofile_line1 = By.xpath(repository.getProperty("USERPROFILE_LINE1"));
	public final By userprofile_line2 = By.xpath(repository.getProperty("USERPROFILE_LINE2"));
//	 public final By userprofile_line3 = By.xpath(repository.getProperty("USERPROFILE_LINE3"));
//	 public final By userprofile_line4 = By.xpath(repository.getProperty("USERPROFILE_LINE4"));
//	 public final By userprofile_line5 = By.xpath(repository.getProperty("USERPROFILE_LINE5"));
//	 public final By userprofile_line6 = By.xpath(repository.getProperty("USERPROFILE_LINE6"));
//	 public final By userprofile_line7 = By.xpath(repository.getProperty("USERPROFILE_LINE7"));
//	 public final By userprofile_line8 = By.xpath(repository.getProperty("USERPROFILE_LINE8"));
//	 public final By userprofile_line9 = By.xpath(repository.getProperty("USERPROFILE_LINE9"));
	public final By userprofile_line10 = By.xpath(repository.getProperty("USERPROFILE_LINE10"));
	public final By userprofile_line11 = By.xpath(repository.getProperty("USERPROFILE_LINE11"));
	public final By userprofile_line12 = By.xpath(repository.getProperty("USERPROFILE_LINE12"));
	public final By userprofile_line13 = By.xpath(repository.getProperty("USERPROFILE_LINE13"));
//	 public final By userprofile_line14 = By.xpath(repository.getProperty("USERPROFILE_LINE14"));
//	 public final By userprofile_line16 = By.xpath(repository.getProperty("USERPROFILE_LINE16"));
//	 public final By userprofile_line17 = By.xpath(repository.getProperty("USERPROFILE_LINE17"));
//	 public final By userprofile_line18 = By.xpath(repository.getProperty("USERPROFILE_LINE18"));
	public final By blenderasset_dot = By.xpath(repository.getProperty("BLENDERASSET_DOT"));
	public final By extruderasset_dot = By.xpath(repository.getProperty("EXTRUDERASSET_DOT"));
	public final By hauloffasset_dot = By.xpath(repository.getProperty("HAULOFFASSET_DOT"));
	public final By thermoformerasset_dot = By.xpath(repository.getProperty("THERMOFORMERASSET_DOT"));
	public final By trimpressasset_dot = By.xpath(repository.getProperty("TRIMPRESSASSET_DOT"));
	public final By grinderasset_dot = By.xpath(repository.getProperty("GRINDERASSET_DOT"));
	public final By systemasset_dot = By.xpath(repository.getProperty("SYSTEMASSET_DOT"));
	public final By assignedfloaters_text = By.xpath(repository.getProperty("ASSIGNEDFLOATERS_TEXT"));
	public final By nofloaters_text = By.xpath(repository.getProperty("NOFLOATERS_TEXT"));
	public final By floater_text = By.xpath(repository.getProperty("FLOATER_TEXT"));
	public final By floater1_text = By.xpath(repository.getProperty("FLOATER1_TEXT"));
	public final By floater2_text = By.xpath(repository.getProperty("FLOATER2_TEXT"));
	public final By production_download_report = By.xpath(repository.getProperty("PRODUCTION_DOWNLOAD_REPORT"));
	public final By download_report = By.xpath(repository.getProperty("DOWNLOAD_REPORT"));
	public final By production_report = By.xpath(repository.getProperty("PRODUCTION_REPORT"));
	public final By time_dropdown = By.xpath(repository.getProperty("TIME_DROPDOWN"));
	public final By prod_download = By.xpath(repository.getProperty("PROD_DOWNLOAD"));
	public final By report_date = By.xpath(repository.getProperty("REPORT_DATE"));
	public final By close = By.xpath(repository.getProperty("CLOSE"));
	public final By eol_text = By.xpath(repository.getProperty("EOL_TEXT"));
	public final By eol_line = By.xpath(repository.getProperty("EOL_LINES"));
	public final By eol_oee_test = By.xpath(repository.getProperty("EOL_OEE_TEST"));
	public final By eol_total_downtime = By.xpath(repository.getProperty("EOL_DOWNTIME_TOTAL"));
	public final By eol_floatertext = By.xpath(repository.getProperty("EOL_FLOATER_TEXT"));
	public final By plant_name_text = By.className(repository.getProperty("PLANTNAME_TEXT"));
	public final By plant_line_no = By.xpath(repository.getProperty("LINE_NUMBER_COUNT"));
	public final By plantShiftCount = By.xpath(repository.getProperty("SHIFT_COUNT"));

}
